// Supported market indexes for the platform
export const SUPPORTED_PERP_MARKET_INDEXES = [
  2,   // ETH-PERP
  0,   // SOL-PERP
  1,   // BTC-PERP
  59,  // HYPE-PERP
  79,  // ZEC-PERP
  23,  // WIF-PERP
  4,   // 1MBONK-PERP
  24,  // JUP-PERP
  76,  // ASTER-PERP
  9,   // SUI-PERP
  20,  // JTO-PERP
  73,  // PAXG-PERP
  13,  // XRP-PERP
  64,  // TRUMP-PERP
  30,  // DRIFT-PERP
  14,  // HNT-PERP
  15,  // INJ-PERP
  71,  // FARTCOIN-PERP
  3,   // APT-PERP
  34,  // POPCAT-PERP
  77,  // XPL-PERP
  22,  // AVAX-PERP
  80,  // MNT-PERP
  16,  // LINK-PERP
  66,  // BERA-PERP
  26,  // TAO-PERP
  62,  // PENGU-PERP
  72,  // ADA-PERP
  78,  // 2Z-PERP
  74,  // LAUNCHCOIN-PERP
  28,  // KMNO-PERP
  8,   // BNB-PERP
  7,   // DOGE-PERP
  29,  // TNSR-PERP
  60,  // LTC-PERP
  21,  // SEI-PERP
  81,  // 1KPUMP-PERP
  56,  // RAY-PERP
  10,  // 1MPEPE-PERP
  18,  // PYTH-PERP
  31,  // CLOUD-PERP
  70,  // IP-PERP
  42,  // TON-PERP
  69,  // KAITO-PERP
  19,  // TIA-PERP
  61,  // ME-PERP
  6,   // ARB-PERP
  12,  // RENDER-PERP
  27,  // W-PERP
  5,   // POL-PERP
  11,  // OP-PERP
];
